services:
  kidsapp-backend:
    depends_on:
      - database
    image: ghcr.io/devinblackblood/swt2-kidsapp/kidsapp-ui:a3022950105c491bee560e39587267fa62c09f35
    ports:
      - "8081:8081"
  api-backend:
    depends_on:
      - database
    image: ghcr.io/devinblackblood/swt2-kidsapp/kidsapp-ui:a3022950105c491bee560e39587267fa62c09f35
    ports:
      - "8080:8080"
  kidsapp-ui:
    depends_on:
      - database
    image: ghcr.io/devinblackblood/swt2-kidsapp/kidsapp-ui:a3022950105c491bee560e39587267fa62c09f35
    ports:
      - "4200:4200"
  database:
    image: postgres:latest
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: korkmaz
      POSTGRES_DB: kidsapp
    volumes:
      - ./postgres:/var/lib/postgres
  mqtt-broker:
    depends_on:
      - database
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "1883:1833"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    security_opt:
      - no-new-privileges:true