services:
  kidsapp-backend:
    build:
      context: ./kidsapp-backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
  api-backend:
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8081:8081"
  kidsapp-ui:
    build:
      context: ./kidsapp-ui
      dockerfile: Dockerfile
    ports:
        - "80:80"
  database:
    image: postgres:latest
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: korkmaz
      POSTGRES_DB: kidsapp
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mqtt-broker:
    depends_on:
      - database
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "1883:1833"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    security_opt:
      - no-new-privileges:true