networks:
  kidsapp-net:

services:
  kidsapp-backend:
    image: ghcr.io/devinblackblood/swt2-kidsapp/kidsapp-backend:f23c3718ffb96387cd07ab198b1e3f8b2565dcd4
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/kidsapp
    depends_on:
      - database
      - mqtt-broker
    ports:
      - "8080:8080"
    networks:
      - kidsapp-net
  api-backend:
    image: ghcr.io/devinblackblood/swt2-kidsapp/kidsapp-backend:f23c3718ffb96387cd07ab198b1e3f8b2565dcd4
    depends_on:
      - database
    ports:
      - "8081:8081"
    networks:
      - kidsapp-net
  kidsapp-ui:
    image: ghcr.io/devinblackblood/swt2-kidsapp/kidsapp-backend:f23c3718ffb96387cd07ab198b1e3f8b2565dcd4
    ports:
        - "80:80"
    networks:
      - kidsapp-net
  database:
    image: postgres:latest
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: korkmaz
      POSTGRES_DB: kidsapp
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - kidsapp-net
  mqtt-broker:
    depends_on:
      - database
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    security_opt:
      - no-new-privileges:true
    networks:
      - kidsapp-net