/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Anschrift { 
    id?: number;
    strasse?: string;
    plz?: string;
    ort?: string;
    land?: string;
    vorname?: string;
    nachname?: string;
}

