/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { Ticket } from './ticket';
import { Nachricht } from './nachricht';
import { Chat } from './chat';


export interface Benutzer { 
    id?: number;
    vorname?: string;
    nachname?: string;
    email?: string;
    passwort?: string;
    adresse?: Adresse;
    profilebild?: string;
    spitzname?: string;
    gesperrt?: boolean;
    administrator?: boolean;
    tickets?: Array<Ticket>;
    nachrichten?: Array<Nachricht>;
    chats?: Array<Chat>;
}

