/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Benutzer } from './benutzer';
import { Nachricht } from './nachricht';


export interface Chat { 
    id?: number;
    name?: string;
    gruppenbild?: string;
    benutzer?: Array<Benutzer>;
    nachrichten?: Array<Nachricht>;
}

