/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Chat } from './chat';


export interface Nachricht { 
    id?: number;
    inhalt?: string;
    datum?: string;
    chat?: Chat;
}

