/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ticket } from './ticket';
import { Anschrift } from './anschrift';


export interface Rechung { 
    id?: number;
    rechnungsnummer?: number;
    rechnungsanschrift?: string;
    veranstalteranschrift?: Anschrift;
    ausstellungszeitpunkt?: string;
    faelligkeitsdatum?: string;
    pdf?: string;
    ticket?: Ticket;
}

