/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Veranstaltung } from './veranstaltung';
import { Benutzer } from './benutzer';
import { Rechnung } from './rechnung';


export interface Ticket { 
    id?: number;
    pruefwert?: string;
    qeCode?: string;
    teilnehmerAnzahl?: number;
    veranstaltung?: Veranstaltung;
    rechung?: Rechnung;
    benutzers?: Array<Benutzer>;
}

