/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { Benutzer } from './benutzer';


export interface Veranstalter { 
    id?: number;
    adresse?: Adresse;
    veranstalterName?: string;
    email?: string;
    telefonnummer?: string;
    mitglieder?: Array<Benutzer>;
    ansprechpersonen?: Array<Benutzer>;
}

