/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { Benutzer } from './benutzer';


export interface Veranstaltung { 
    id?: number;
    adresse?: Adresse;
    beschreibung?: string;
    veranstaltungName?: string;
    benutzer?: Array<Benutzer>;
}

