name: Pre Merge Checks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [24]
        project:
          - api-backend
          - kidsapp-backend
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '${{ matrix.jdk }}'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven of ${{ matrix.project }}
        if: ${{ matrix.project != '' }}
        working-directory: ${{ matrix.project }}
        run: mvn --batch-mode --update-snapshots verify

  check-ui:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        node: [ 20 ]
        project:
          - kidsapp-ui
    runs-on: ${{ matrix.os }}
    name: Check Angular UI (kidsapp-ui)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node }}'
          cache: 'npm'
          cache-dependency-path: kidsapp-ui/package-lock.json

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: npm ci