name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        jdk: [22]
        project:
          - api-backend
          - kidsapp-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Container Metadata
        id: metadata
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ matrix.project }}
      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Build Jar
        run: |
          cd ${{ matrix.project }}
          mvn --batch-mode --update-snapshots package
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: lower-repo
        name: Convert name of repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.project }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}/${{ matrix.project }}:${{ github.sha }}
          labels: ${{ steps.metadata.outputs.labels }}

  build-ui:
    runs-on: ubuntu-latest
    name: Build Angular UI (kidsapp-ui)
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        node: [ 20 ]
        project:
          - kidsapp-ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker Container Metadata
        id: metadata
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ matrix.project }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: kidsapp-ui/package-lock.json

      - name: Install
        working-directory: ${{ matrix.project }}
        run: npm ci

      - name: Build

        run: |
               cd ${{ matrix.project }}
              npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: lower-repo
        name: Convert name of repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.project }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}/${{ matrix.project }}:${{ github.sha }}
          labels: ${{ steps.metadata.outputs.labels }}