FROM maven:3.9.9-eclipse-temurin-24-alpine
# Set the working directory
WORKDIR /kidsapp-backend

COPY . .
# Run the application
CMD ["java", ".src/main/java/com/swt1/bs/kidsappbackend/KidsappBackendApplication.java"]
EXPOSE 8081